### ISSUE TITLE
Daily updates stopped

### ISSUE THREAD

**Issue by Propaganistas** [disposable/disposable-email-domains#23]
Hi

it seems the daily updates for the domains list stopped on October 30th, 2020.
Perhaps a daily scheduled GitHub Action might be interesting?

Thanks for rebooting the updates!

**Comment by SoftCreatR** [comment]
There are just no new updates, according to https://github.com/disposable/disposable.

**Comment by smeinecke** [comment]
Thanks for the info. There was a bug which stopped updates on https://github.com/disposable/disposable-email-domains. Should be fine now.
