### ISSUE TITLE
googlemail.com, outlook.com are not disposable

### ISSUE THREAD

**Issue by mtmail** [disposable/disposable-email-domains#24]
https://github.com/disposable/disposable-email-domains/commit/7033ee23464677dcc82c89c5cbd1b08c30dc2e7e
added

mail.ru
gmx.com
gmx.es
googlemail.com
outlook.com
yandex.com
ymail.com (yahoo)
zoho.com

which I'd consider freemail, but not disposable.

**Comment by ellavs** [comment]
Yes, I agree too.
mail.ru - popular Russian free mail.
outlook.com - it's mail from Microsoft.
I have mail on both.

**Comment by smeinecke** [comment]
Please add issues on https://github.com/disposable/disposable as this repository just host the generated files and is not monitored.

Just removed source for that domains in https://github.com/disposable/disposable/commit/9889d365a0faa0defc9288afa064254422601ef4

Should be fixed in next update.

**Comment by smeinecke** [comment]
resolved in https://github.com/disposable/disposable-email-domains/commit/842c830d134f05fac34711e3031998a79bda902a
