### ISSUE TITLE
gmx.com listed

### ISSUE THREAD

**Issue by fnetX** [disposable/disposable-email-domains#26]
We've run into issues by using this list, as gmx.com was added in 7033ee23464677dcc82c89c5cbd1b08c30dc2e7, but this offers regular sign-up (similar to many other hosts) and many users seem to rely on it. What was the reason to add this one?

Also, many users probably still use their googlemail addresses, they were listed in this commit, too?

**Comment by smeinecke** [comment]
Thanks for the info. This service only collects data from other lists, which unfortunately sometimes causes legitimate domains to end up on the list. Therefore, we always specify in the `domains_source_map.txt` from which source which domain comes.

In this case the `gmx.com` (which is of course a legitimate email provider like google) came from a new list which was added only a few months ago. I will remove this in the next update.

**Comment by fnetX** [comment]
Thank you very much, for the fix and for maintaining this list.

**Comment by fnetX** [comment]
Hey, the list you just removed appears to be an unmaintained fork of https://github.com/FGRibreau/mailchecker - which appears not to have this issue. Maybe worth a consideration as a data source instead?
